### ISSUE TITLE
There is a corrected formula for paired tests

### ISSUE THREAD

**Issue by gciriani** [stonegold546/cohens_d_calculators#25]
There is a corrected formula for paired tests, dividing the d obtained by sqrt(1-r).  See Cohen J, 1988, p.49, at this link
http://www.utstat.toronto.edu/~brunner/oldclass/378f16/readings/CohenPower.pdf#page=66

**Comment by stonegold546** [comment]
Hello, I think I currently use this formula for the repeated measures approach to computing Cohen's d. See here: https://github.com/stonegold546/cohens_d_calculators#paired-samples-t-test so I'll be closing this issue. Feel free to reopen if you find I'm mistaken. Thank you.
